# this file from docker-compose.workspace, delete mail-server
# default MySQL root password is 123456

version: '3.8'
services:
  mingdaoyun-doc:
    container_name: ${APP_NAME}-doc
    image: registry.cn-hangzhou.aliyuncs.com/mdpublic/mingdaoyun-doc:1.2.0
    user: root
    restart: always
     
  mingdaoyun-community:
    container_name: ${APP_NAME}
    image: registry.cn-hangzhou.aliyuncs.com/mdpublic/mingdaoyun-community:3.1.1
    ports:
     - '${APP_PORT}:38881'
    restart: always
    
networks:
  default:
      name: ${APP_NAME}
